### ISSUE TITLE
remove __pycache__

### ISSUE THREAD

**Issue by tabebqena** [ahmedEid1/E-Learning-Platform#1]
Please remove __pycache__ folders from the repository. This will significantly decrease the total size.

Now, The total size of the repo is about 88 MBs while similar projects has up to 2 MBs.

You can use something like:

    git rm -r */__pycache__

Kindly follow this [link](https://stackoverflow.com/questions/6313126/how-do-i-remove-a-directory-from-a-git-repository)

**Comment by ahmedEid1** [comment]
Yup, I should definitely remove it.
but the reason the repo is so big is the GIFs in the readme, I should move them to some CDN and add link to them not upload them to github :(

thank you for the feedback  👍
